### ISSUE TITLE
Replaced with Retailer V3

### ISSUE THREAD

**Issue by jasperverbeet** [picqer/bol-plaza-php-client#12]
V2 of the plaza API was just updated and is due for closure in about a year. Maybe the README.md should be updated to display this information.

I've started on implementing the api in a [new package here](https://github.com/jasperverbeet/bolcom-retailer-api-v3-php), but it not at all finished.

More info: [https://developers.bol.com/newretailerapiv3/](https://developers.bol.com/newretailerapiv3/)

**Comment by casperbakker** [comment]
We will update our client to be compatible with v3. There is 1 small feature that Bol has to implement so we can use v3 as well, then we will update this client for v3.

Your client also looks solid. Best of luck!
