### ISSUE TITLE
Bol.com retailer API v3

### ISSUE THREAD

**Issue by Pwuts** [picqer/bol-plaza-php-client#13]
The Bol.com retailer API v3 has arrived some time ago, and v2 will be deprecated by April 2020. It might be useful to migrate this package to the v3 API.
The new version uses JSON instead of XML which makes it much nicer to use (imo) and some objects have been restructured.

**Comment by casperbakker** [comment]
That is right @Pwuts. We choose to build a complete new client for the new Retailer API. You can find it here: https://github.com/picqer/bol-retailer-php-client

In our opinion the interface of this new client is a little better.
