### ISSUE TITLE
Updating master with v2 and tagging a release version

### ISSUE THREAD

**Issue by Soneritics** [picqer/bol-plaza-php-client#3]
Hi,

I just came across this repo while needing to switch to the BOL Plaza API V2.

I have tested a few of the functions, like fetching open orders, cancelling orders and processing shipments. All works fine, well done!

Now my question is; is there a reason the v2 branch is not merged onto the master yet? The reason for my question is that there's only one release tag. When I use composer to checkout the package, I still get this old master version which uses the old V1 API.

For my automated build process it would be nice to be able to use composer, instead of having to checkout as a Git-submodule and writing my own autoloader. If the package is not yet stable, I understand that it's not merged onto the master and tagged as a release version. But for as far as I can see, all work considering the new API version is done.

Again; nice work!

**Comment by casperbakker** [comment]
Hi @Soneritics,

We forgot to tag the version for v1, so most use this library with dev-master. When we started on v2, we tagged v1, but we did not release the v2 yet because we did not want to release that one yet to everybody. But it is save to use, we use it in production for a couple of weeks now.

But you can use it with composer even without a release, you can tag the specific commit. Like this:

```
        "picqer/bol-plaza-php-client": "dev-master#e68b9df6a036518b0d8012a24dd8ca1abe5b36aa",
```

**Comment by Soneritics** [comment]
Hi @casperbakker,

I have put it into production yesterday and all works well.

Pointing Composer directly to a commit isn't really best practice, but good enough :)

Thanks again!

**Comment by casperbakker** [comment]
> Pointing Composer directly to a commit isn't really best practice, but good enough :)

True, but it is a best practice if the developer did not put out a proper release yet. Instead of binding to dev-master. So all shame on us. :)

**Comment by xewl** [comment]
Using the same commit to force to the v2 version.
Would love to put ~2.0 tho' :)
