### ISSUE TITLE
updateOfferStock deprecated since v2

### ISSUE THREAD

**Issue by dnsBlah** [picqer/bol-plaza-php-client#6]
when will the client and entities be updated for the V2 ?

**Comment by casperbakker** [comment]
We will update specific entities when we need them ourselves. But if you need something, feel free to create a Pull Request with the new entities.

**Comment by dnsBlah** [comment]
thank you, but i will just use wienkit.

**Comment by casperbakker** [comment]
Sure, no hard feeling
